### ISSUE TITLE
How to add child roles for a role?

### ISSUE THREAD

**Issue by baorv** [YaroslavMolchan/rbac#6]
How can I add child roles for a role like Yii2 framework here. 
http://www.yiiframework.com/doc-2.0/guide-security-authorization.html#using-migrations
```php
$author = $auth->createRole('author');
$auth->add($author);
$auth->addChild($author, $createPost);
$admin = $auth->createRole('admin');
$auth->add($admin);
$auth->addChild($admin, $updatePost);
$auth->addChild($admin, $author);
```

**Comment by bleuscyther** [comment]
i use this in the controller with some boot logic on the model file :
 https://github.com/lazychaser/laravel-nestedset.

In the past i used [ OWASP RBAC](https://github.com/OWASP/rbac) but its no longer maintained.

**Comment by baorv** [comment]
Thank you for your references!
